apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-code-with-quarkus-qixz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-code-with-quarkus-qixz
    app.kubernetes.io/part-of: test-rhtap-55-app
  name: devfile-sample-code-with-quarkus-qixz
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: devfile-sample-code-with-quarkus-qixz
status:
  loadBalancer: {}
